In [5]:
import torch 

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y,  x * y, x / y, x**y 

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [6]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [7]:
x[2]

tensor(2)

In [8]:
len(x)

3

In [9]:
x.shape

torch.Size([3])

In [11]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [12]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [13]:
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [14]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B= A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [15]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])